spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/labo3
    username: postgres
    password: 5427
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true